#!/usr/bin/env node
// pipelines/07-anatomist-review/promote.mjs
//
// Phase 1 step P1.16 - promote content records from `pending` to `reviewed`
// based on an anatomist-edited review-queue manifest.
//
// Workflow:
//   1. Anatomist reviews the Markdown packet generated by generate-packet.mjs.
//   2. Anatomist (or a human helper) mirrors their decisions into
//      tests/review-queue/<batch_id>/manifest.json by editing per-item:
//        - status: "queued" -> "approved" | "approved_with_edits" | "rejected" | "needs_research"
//        - decision: short string describing the decision
//        - reviewed_at: ISO datetime
//        - reviewer_notes: optional free text
//      and at the top level:
//        - anatomist.name / .credentials / .contact filled in
//        - status: "queued" -> "in_review" -> "complete"
//   3. This script reads the manifest, and for every item with
//      status === "approved" (and a non-empty decision), opens the
//      corresponding content record, sets confidence="reviewed",
//      reviewed_by=<anatomist.name>, bumps last_updated to now, and
//      appends reviewer_notes -> review_notes if non-empty.
//   4. Modified records are validated against content-record-schema.json
//      before being written to disk. Any validation failure aborts the
//      entire batch (nothing is written) and exits non-zero.
//
// Flags:
//   --dry-run               do not write any files; print what would change.
//   --manifest <path>       override the default manifest path
//                           (default: tests/review-queue/<batch_id>/manifest.json).
//   --batch <id>            batch id (default: 2026-05-11-batch-1).
//
// "approved_with_edits" is intentionally NOT auto-promoted: such records
// imply the prose itself needs revision by the Content agent before the
// schema-required `reviewed` flag is set. Similarly "rejected" and
// "needs_research" stay `pending` (a future Content dispatch handles them).

import { readdir, readFile, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { dirname, resolve, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import Ajv2020 from '../../app/web/node_modules/ajv/dist/2020.js';
import addFormatsModule from '../../app/web/node_modules/ajv-formats/dist/index.js';

const addFormats = addFormatsModule.default ?? addFormatsModule;

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, '..', '..');
const contentDir = resolve(repoRoot, 'data', 'canonical', 'ontology', 'content');
const schemaPath = resolve(repoRoot, 'app', 'shared', 'schema', 'content-record-schema.json');

// --- Parse args ---

const args = process.argv.slice(2);
let dryRun = false;
let batchId = '2026-05-11-batch-1';
let manifestOverride = null;
for (let i = 0; i < args.length; i++) {
  const a = args[i];
  if (a === '--dry-run') dryRun = true;
  else if (a === '--manifest') manifestOverride = args[++i];
  else if (a === '--batch') batchId = args[++i];
  else {
    console.error(`Unknown arg: ${a}`);
    process.exit(2);
  }
}

const manifestPath =
  manifestOverride ??
  resolve(repoRoot, 'tests', 'review-queue', batchId, 'manifest.json');

// --- Load schema + ajv ---

if (!existsSync(schemaPath)) {
  console.error(`FAIL schema not found at ${schemaPath}`);
  process.exit(1);
}
const schema = JSON.parse(await readFile(schemaPath, 'utf8'));
const ajv = new Ajv2020({ strict: false, allErrors: true });
addFormats(ajv);
const validate = ajv.compile(schema);

// --- Load manifest ---

if (!existsSync(manifestPath)) {
  console.error(`FAIL manifest not found at ${manifestPath}`);
  process.exit(1);
}
const manifest = JSON.parse(await readFile(manifestPath, 'utf8'));

const anatomistName = manifest?.anatomist?.name;
if (!anatomistName || anatomistName === 'TBD' || anatomistName.trim() === '') {
  console.error(
    'FAIL manifest.anatomist.name is not set (still "TBD" or empty). Refusing to promote without a reviewer identity (schema requires reviewed_by for reviewed records).',
  );
  process.exit(1);
}

const items = Array.isArray(manifest.items) ? manifest.items : [];
if (items.length === 0) {
  console.error('FAIL manifest has no items');
  process.exit(1);
}

const promoteCandidates = items.filter((it) => it.status === 'approved');
const otherStatuses = items.filter((it) => it.status !== 'approved');

console.log(`Manifest: ${manifestPath}`);
console.log(`Batch: ${manifest.batch_id ?? batchId}`);
console.log(`Anatomist: ${anatomistName}`);
console.log(`Items total: ${items.length}`);
console.log(`Items to promote (status="approved"): ${promoteCandidates.length}`);
console.log(`Items to leave alone (other statuses): ${otherStatuses.length}`);
console.log(`Mode: ${dryRun ? 'DRY-RUN (no writes)' : 'LIVE (will write)'}`);
console.log('');

if (promoteCandidates.length === 0) {
  console.log('Nothing to promote. Done.');
  process.exit(0);
}

// --- Prepare modifications in memory; validate every one; abort on any failure ---

const now = new Date().toISOString();
const planned = [];
const failures = [];

for (const item of promoteCandidates) {
  if (!item.decision || String(item.decision).trim() === '') {
    failures.push(
      `${item.structure_id}: status='approved' but decision field is empty; refusing to promote without a recorded decision`,
    );
    continue;
  }

  const filePath = join(contentDir, item.filename);
  if (!existsSync(filePath)) {
    failures.push(`${item.structure_id}: content file not found at ${filePath}`);
    continue;
  }

  let record;
  try {
    record = JSON.parse(await readFile(filePath, 'utf8'));
  } catch (err) {
    failures.push(`${item.structure_id}: cannot parse ${filePath}: ${err.message}`);
    continue;
  }

  // Sanity check: the file must describe the same structure_id.
  if (record.structure_id !== item.structure_id) {
    failures.push(
      `${item.structure_id}: file ${item.filename} contains structure_id="${record.structure_id}"; manifest/file mismatch`,
    );
    continue;
  }

  // Schema requires citations (minItems 1) when confidence='reviewed'.
  // P1.15 records were authored with citations, but guard against an
  // empty citations array.
  if (!Array.isArray(record.citations) || record.citations.length === 0) {
    failures.push(
      `${item.structure_id}: content record has no citations; schema requires minItems 1 for reviewed records (P1.15 should have populated this)`,
    );
    continue;
  }

  const updated = {
    ...record,
    confidence: 'reviewed',
    reviewed_by: anatomistName,
    last_updated: now,
  };
  const notes = item.reviewer_notes;
  if (notes && String(notes).trim() !== '') {
    updated.review_notes = String(notes);
  }

  const valid = validate(updated);
  if (!valid) {
    const errs = (validate.errors ?? [])
      .map((e) => `${e.instancePath || '<root>'}: ${e.message} ${JSON.stringify(e.params)}`)
      .join('; ');
    failures.push(`${item.structure_id}: post-promotion record fails schema: ${errs}`);
    continue;
  }

  planned.push({ item, filePath, before: record, after: updated });
}

if (failures.length > 0) {
  console.error(`Validation/preparation failures (${failures.length}); aborting batch:`);
  for (const f of failures) console.error(`  FAIL ${f}`);
  process.exit(1);
}

// --- All-or-nothing write phase ---

if (dryRun) {
  console.log(`DRY-RUN would promote ${planned.length} record(s):`);
  for (const { item } of planned) {
    console.log(`  WOULD-PROMOTE ${item.structure_id}  (${item.filename})  -> reviewed_by="${anatomistName}"`);
  }
  console.log('');
  console.log(`DRY-RUN result: ${planned.length} would-promote, 0 failed. No files written.`);
  process.exit(0);
}

let written = 0;
for (const { item, filePath, after } of planned) {
  await writeFile(filePath, JSON.stringify(after, null, 2) + '\n', 'utf8');
  console.log(`  PROMOTED ${item.structure_id}  (${item.filename})`);
  written += 1;
}

console.log('');
console.log(`Result: ${written} promoted, 0 failed.`);
process.exit(0);
